
import { v4 as uuidv4 } from 'uuid';
import { type Schema } from '@/amplify/data/resource';
type MyMonsterStatblock = Schema['MonsterStatblock']['type'];

export function createDefaultKnightStatblock(ownerId: string): Schema['MonsterStatblock']['type']{
    
    const now = new Date().toISOString();

    // The Omit utility type is used because 'createdAt' and 'updatedAt' 
    // are typically generated by the database upon saving.
    return {
        // --- Required Fields (from schema) ---
        id: uuidv4(),
        ownerId: ownerId,
        name: 'Knight',
        createdAt: now,
        updatedAt: now,
        
        // --- Core Stats ---
        desc: 'A skilled warrior trained for war and tested in battle.',
        size: 'Medium',
        type: 'humanoid',
        subtype: '(any race)',
        alignment: 'any alignment',
        challenge_rating: '3',
        cr: 3.0,
        
        // --- Defense ---
        armor_class: 18,
        armor_desc: 'plate armor',
        hit_points: 52,
        current_hit_points: 52, // Start with full HP
        hit_dice_num: 8,
        hit_dice: '8d8 + 16',
        
        // --- Speed ---
        speed: {
            walk: 30,
            swim: 0,
            fly: 0,
            climb: 0,
            burrow: 0,
            hover: false,
            notes: null,
        },
        
        // --- Abilities & Modifiers ---
        strength: 16,
        dexterity: 11,
        constitution: 14,
        intelligence: 11,
        wisdom: 11,
        charisma: 15,
        
        // Saving Throws: CON +4, WIS +2 (based on base stat + Prof. Bonus of +2)
        strength_save: 3, 
        dexterity_save: 0, 
        constitution_save: 4, 
        intelligence_save: 0, 
        wisdom_save: 2, 
        charisma_save: 2, 
        save_proficiencies: ['CON', 'WIS'],
        
        // --- Senses/Skills/Languages ---
        perception: 10,
        senses: 'passive Perception 10',
        languages: 'any one language (usually Common)',
        
        // Initialize other custom types to empty objects/arrays as per schema
        skills: {},
        skill_proficiencies: {},
        damage_vulnerability_list: [],
        damage_resistance_list: [],
        damage_immunity_list: [],
        condition_immunity_list: ['Frightened'],
        
        // --- Special Abilities (Traits) ---
        special_abilities: [
            {
                name: 'Brave',
                desc: 'The knight has advantage on saving throws against being frightened.',
            },
        ],
        
        // --- Actions ---
        actions: [
            {
                name: 'Multiattack',
                desc: 'The knight makes two melee attacks.',
                damage: [], // Multiattack itself has no damage dice
            },
            {
                name: 'Greatsword',
                type: 'Melee Weapon Attack',
                attack_bonus: '+5',
                reach: 5, // 5 ft.
                desc: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 10 (2d6 + 3) slashing damage.',
                damage: [
                    {
                        damage_dice: '2d6+3',
                        damage_type: 'slashing',
                    },
                ],
            },
            {
                name: 'Heavy Crossbow',
                type: 'Ranged Weapon Attack',
                attack_bonus: '+2',
                short_range: 100,
                long_range: 400,
                desc: 'Ranged Weapon Attack: +2 to hit, range 100/400 ft., one target. Hit: 5 (1d10) piercing damage.',
                damage: [
                    {
                        damage_dice: '1d10',
                        damage_type: 'piercing',
                    },
                ],
            },
            {
                name: 'Leadership (Recharges after a Short or Long Rest)',
                desc: 'For 1 minute, the knight can utter a special command or warning whenever a nonhostile creature that it can see within 30 feet of it makes an attack roll or a saving throw. The creature can add a d4 to its roll provided it can hear and understand the knight. A creature can benefit from only one Leadership die at a time. This effect ends if the knight is incapacitated.',
                damage: [],
            },
        ],
        
        // --- Bonus Actions & Reactions ---
        bonus_actions: [],
        reactions: [
            {
                name: 'Parry',
                desc: 'The knight adds 2 to its AC against one melee attack that would hit it. To do so, the knight must see the attacker and be wielding a melee weapon.',
            },
        ],
        
        // --- Legendary/Mythic Actions (Empty for Knight) ---
        legendary_desc: null,
        legendary_actions: [],
        mythic_desc: null,
        mythic_actions: [],
    };
}